# Generated by Django 4.2.21 on 2025-05-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book2',
        ),
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Catagory2',
        ),
    ]
