# Generated by Django 4.2.21 on 2025-05-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_book_book2_rename_catagory_catagory2'),
    ]

    operations = [
        migrations.AddField(
            model_name='book2',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.catagory2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/imgs'),
        ),
    ]
