# Generated by Django 4.2.21 on 2025-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book2_catagory_book2_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book2',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
